name: Generate Star History

on:
  schedule:
    - cron: '0 1 * * *'   # 每天上午 9:00（UTC 时间）

  workflow_dispatch:       # 也支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up pnpm
        run: npm install -g pnpm

      - name: Install Node.js dependencies and run dev
        run: |
          pnpm install
          pnpm dev &     # 如果 dev 是长时间运行服务，这一行可能要删掉
          sleep 5       # 等待服务就绪，或根据需要调整

      - name: Upgrade pip and install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirement.txt ]; then pip install -r requirement.txt; fi

      - name: Run Python script to generate image
        run: python test.py
        env:
          ACCESS_TOKEN: ${{ secrets.ADMINTOKEN }}


      - name: Git add and commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update star_history.png [$(date +'%Y-%m-%d')]" || echo "Nothing to commit"
        env:
          ADMIN_TOKEN: ${{ secrets.ADMINTOKEN }}


      - run: git remote -v

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.ADMINTOKEN}}
          branch: main